### ISSUE TITLE
Overlay position

### ISSUE THREAD

**Issue by oleks12345** [boonwin/BoonwinsBattlegroundsTracker#1]
Ability to set rank overlay position would be very helpful.
For example having "Placement of the day" in bottom corner instead of top.

**Comment by b00nwin** [comment]
so far you can only change it from left to right top corner, i dont really know how i can get the position from deck tracker, but its still in my to do list.

**Comment by oleks12345** [comment]
I'm not sure how does hdt dev api works, but maybe just allowing user to optionally type positions in pixels

**Comment by b00nwin** [comment]
i added some stuff but its quite buggy if you want you can try it out
