### ISSUE TITLE
Error System.DivideByZeroException

### ISSUE THREAD

**Issue by QWhyte** [boonwin/BoonwinsBattlegroundsTracker#13]
I have issue, i dont know what to do....
This error come when I want to turn on the plugin by moving the slider

HDT 1.13.20
Plugin version: 0.0.13

Make sure you are using the latest version of the Plugin and HDT.

System.DivideByZeroException: Nastąpiła próba podzielenia przez zero.
w BoonwinsBattlegroundTracker.GameHistoryOverlay.showAvgRanks()
w BoonwinsBattlegroundTracker.GameHistoryOverlay..ctor()
w BoonwinsBattlegroundTracker.BgMatchDataPlugin.OnLoad()
w Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load() w D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:wiersz 93

**Comment by b00nwin** [comment]
use newst version uploaded today
