### ISSUE TITLE
'Quilboar' update now bans 3 tribes per game

### ISSUE THREAD

**Issue by ChrisNolan** [boonwin/BoonwinsBattlegroundsTracker#17]
> Quilboar have been added as a new Battlegrounds minion type! There will still be five minion types per Battlegrounds game once Quilboar are added, meaning that three minion types will be excluded from each game.

**Comment by AgraveiNstream** [comment]
Hope Boonwin will return and polish his child again ;)

**Comment by ChrisNolan** [comment]
This was addressed in the 1.11 release I believe, so the issue can be closed.

There is a problem that will come up when Quilboar are not included in ever game, in that the image associated with the Quilboars is mis-named in the 'Img' folder of the plugin.  It should be 'quilboar.png', not 'quilboars.png'
