### ISSUE TITLE
Antiwirus/Malwarebytes problem

### ISSUE THREAD

**Issue by AgraveiNstream** [boonwin/BoonwinsBattlegroundsTracker#18]
Boonwin do you want to tell us something? Kappa

https://imgur.com/a/RJ7aUUG

i need to put those files into quarantine

**Comment by b00nwin** [comment]
i dont know what does that mean, its just a libary from microsoft, that i use to be able to use updates automatically instead of doing it youself. i think malewarebytes doesnt like this in gernal because you could use it for some bad stuff but i didnt...
