### ISSUE TITLE
Weird Issue - Exception

### ISSUE THREAD

**Issue by mistergom** [boonwin/BoonwinsBattlegroundsTracker#19]
Hello,
I'm (French and) using BoonwinsBattlegroundsTracker and sometimes I notice weird issue (red message in HD), then BoonwinsBattlegroundsTracker "crashes". HDT and BBT are both updated to latest version.
Here are the screenshots of the issue in HDT:
![Screenshot_000917](https://user-images.githubusercontent.com/46899060/134812719-787ff240-0fc1-409e-aa98-33a58b09a889.jpg)
![Screenshot_000916](https://user-images.githubusercontent.com/46899060/134812723-354f16a9-98b9-4d7c-a256-bf3bece79a13.jpg)

Copy of the message (some parts are in French...):
Make sure you are using the latest version of the Plugin and HDT.

System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : value
   à System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   à System.String.Contains(String value)
   à BoonwinsBattlegroundTracker.Leaderboard.<>c__DisplayClass12_0.<GetLeaderboard>b__1(Leaderboard d)
   à System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   à System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   à BoonwinsBattlegroundTracker.Leaderboard.<>c__DisplayClass12_0.<GetLeaderboard>b__0()
   à System.Threading.Tasks.Task.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à BoonwinsBattlegroundTracker.Leaderboard.<GetLeaderboard>d__12.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à BoonwinsBattlegroundTracker.BgMatchData.<UpdateLeaderboardData>d__57.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by b00nwin** [comment]
there is a field where you can enter your ingame name in the settings, do it and it should work.
