### ISSUE TITLE
Show "Placement of the day" during game

### ISSUE THREAD

**Issue by oleks12345** [boonwin/BoonwinsBattlegroundsTracker#2]
as in title, could you add option to show "Placement of the day" during game, not only in lobby.

**Comment by b00nwin** [comment]
ill add this option with the next update, it used to be like that but people wanted it to be gone while playing because it might block the enemies avatar

//edit i just added this function but i have to debug ist, but ill maybe just get to it tomorrow.

**Comment by b00nwin** [comment]
its possible  now
