### ISSUE TITLE
Banned Tribe is hard to see on mobile

### ISSUE THREAD

**Issue by oleks12345** [boonwin/BoonwinsBattlegroundsTracker#3]
I think that it would be a great option to give user ability to choose between classical banned tribe and showing picture over deck with banned tribe.

example 
![image](https://user-images.githubusercontent.com/19672992/90508202-91a2ee80-e157-11ea-8b38-3b994cd32292.png)

example icons you can use (thanks to AgraveiN from twitch) 
[ikonkihs.zip](https://github.com/boonwin/BoonwinsBattlegroundsTracker/files/5090059/ikonkihs.zip)

**Comment by b00nwin** [comment]
thanks for the icons this was also already on my todo list :)

**Comment by b00nwin** [comment]
its possible now
