### ISSUE TITLE
When spectating someone plugin records his place in own statistic

### ISSUE THREAD

**Issue by Dego1n** [boonwin/BoonwinsBattlegroundsTracker#5]
So if you spectate someone and player finishes his game, his plays will be counted as your own in statistic of the day. Can something be done about this?

**Comment by TranRed** [comment]
You can utilize the attribute `Core.Game.Spectator`. It will be true if it was a game from spectator mode.

Checking before all this should do the trick:
https://github.com/boonwin/BoonwinsBattlegroundsTracker/blob/9084fe1ca137543688999e9369267cf96eef3606/BoonwinsBattlegroundTracker/BgMatchData.cs#L101-L116

**Comment by b00nwin** [comment]
Thanks, I saw that already but im focusing on some other stuff right now but i will look into it.

**Comment by b00nwin** [comment]
it should be fixed now
