### ISSUE TITLE
Ban problems

### ISSUE THREAD

**Issue by AgraveiNstream** [boonwin/BoonwinsBattlegroundsTracker#7]
Pirates are not banned 
https://imgur.com/a/BJE4GE9
we can play them
sometimes its buggin when picking Pirates/Murlocs

**Comment by b00nwin** [comment]
yeah i know in my version i fixed it if you see murlocs pirates baned it might not be true. its kinda a hdt problem i guess, for me i build in a workaround so it should work in the future still testing it

**Comment by b00nwin** [comment]
its fixed now
