### ISSUE TITLE
Ban icon getting shown and stuck in other game modes

### ISSUE THREAD

**Issue by AnacondaHL** [boonwin/BoonwinsBattlegroundsTracker#8]
I've seen it in constructed and arena, and it's only the ban icon image, but it gets stuck on-screen. It even persists if I disable the addon in HDT.

**Comment by b00nwin** [comment]
i know also annoys me ill fix it soon

**Comment by b00nwin** [comment]
i think i fixed it with the last version at least it is not shown for me
