### ISSUE TITLE
`System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Charge71** [boonwin/BoonwinsBattlegroundsTracker#9]
Tracker version: 1.13.15
Plugin version: 0.0.9

`System.NullReferenceException: Object reference not set to an instance of an object.
   in BoonwinsBattlegroundTracker.BgMatchData.SetMissingRace()
   in BoonwinsBattlegroundTracker.BgMatchData.<GameStart>d__28.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by AnacondaHL** [comment]
same issue, here's the output:

Make sure you are using the latest version of the Plugin and HDT.

System.NullReferenceException: Object reference not set to an instance of an object.
   at BoonwinsBattlegroundTracker.BgMatchData.SetMissingRace()
   at BoonwinsBattlegroundTracker.BgMatchData.<GameStart>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by b00nwin** [comment]
i made a new version, i dont really know what to do with this error code, when did this happen? at the beginning of a round?

**Comment by Charge71** [comment]
Unfortunately I can't say, found it in the log at the end of a game...

**Comment by QWhyte** [comment]
I have issue, i dont know what to do....
This error come when I want to turn on the plugin by moving the slider

HDT 1.13.20
Plugin version: 0.0.13

Make sure you are using the latest version of the Plugin and HDT.

System.DivideByZeroException: Nastąpiła próba podzielenia przez zero.
   w BoonwinsBattlegroundTracker.GameHistoryOverlay.showAvgRanks()
   w BoonwinsBattlegroundTracker.GameHistoryOverlay..ctor()
   w BoonwinsBattlegroundTracker.BgMatchDataPlugin.OnLoad()
   w Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load() w D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:wiersz 93

**Comment by b00nwin** [comment]
you guys still have those? i think it might be happening when you get high rank and didnt enter a name in setting for leaderboard, then i saw it somewhere else, i need to look into it

**Comment by Charge71** [comment]
Seeing this now (version 0.0.0.15):

```
System.ArgumentNullException: Value cannot be null.
Nome parametro: value
   in System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   in System.String.Contains(String value)
   in BoonwinsBattlegroundTracker.Leaderboard.<>c__DisplayClass12_0.<GetLeaderboard>b__1(Leaderboard d)
   in System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   in System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   in BoonwinsBattlegroundTracker.Leaderboard.<>c__DisplayClass12_0.<GetLeaderboard>b__0()
   in System.Threading.Tasks.Task.InnerInvoke()
   in System.Threading.Tasks.Task.Execute()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   in BoonwinsBattlegroundTracker.Leaderboard.<GetLeaderboard>d__12.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   in BoonwinsBattlegroundTracker.BgMatchData.<UpdateLeaderboardData>d__47.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
```

**Comment by b00nwin** [comment]
> Seeing this now (version 0.0.0.15):
> 
> ```
> System.ArgumentNullException: Value cannot be null.
> Nome parametro: value
>    in System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
>    in System.String.Contains(String value)
>    in BoonwinsBattlegroundTracker.Leaderboard.<>c__DisplayClass12_0.<GetLeaderboard>b__1(Leaderboard d)
>    in System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    in System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
>    in BoonwinsBattlegroundTracker.Leaderboard.<>c__DisplayClass12_0.<GetLeaderboard>b__0()
>    in System.Threading.Tasks.Task.InnerInvoke()
>    in System.Threading.Tasks.Task.Execute()
> --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
>    in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    in System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    in BoonwinsBattlegroundTracker.Leaderboard.<GetLeaderboard>d__12.MoveNext()
> --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
>    in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    in System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    in BoonwinsBattlegroundTracker.BgMatchData.<UpdateLeaderboardData>d__47.MoveNext()
> --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
> ```

i figured out what it is, you need to go to the plugin settings and activate leaderboard then you can write your name in the textbox after that the error should be gone, ill update it soon

**Comment by Charge71** [comment]
How do I activate leaderboard? I can't see this configuration in the plugin settings.
Thanks.

**Comment by b00nwin** [comment]
> How do I activate leaderboard? I can't see this configuration in the plugin settings.
> Thanks.

https://i.imgur.com/LjTMjxC.png first click plugins then click on the name of plugin then click leaderboard then enter your name

**Comment by Charge71** [comment]
Thank you, since I entered the name the error is not happened any more.
